# 1-Importaciones

In [132]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 2-Cargar los Datos

In [133]:
df = pd.read_csv('/workspaces/Elreno23-machine-learning-python-template/data/raw/02-linear-regression-medical_insurance_cost.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# 3-Exploracion Inicial

In [134]:
df.info()
df.shape
df.isna().sum()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

,count,mean,std,min,25%,50%,75%,max
age,1338.0,39.207025,14.049960,18.0000,27.00000,39.000,51.000000,64.00000
bmi,1338.0,30.663397,6.098187,15.9600,26.29625,30.400,34.693750,53.13000
children,1338.0,1.094918,1.205493,0.0000,0.00000,1.000,2.000000,5.00000
charges,1338.0,13270.422265,12110.011237,1121.8739,4740.28715,9382.033,16639.912515,63770.42801

## Conclusiones

La mayoría de los asegurados tiene entre 0 y 2 hijos, el IMC promedio indica sobrepeso, y el coste del seguro (charges) está muy disperso.

# 4-Limpieza de Datos(Inicial)

In [135]:
df = df.drop_duplicates() #Eliminamos duplicados

#iteramos osbre las columnas numericas ignorando la variable objetivo y children(queremos saber si la persona no tiene hijos)
cols_to_check = [col for col in df.select_dtypes(include="number").columns if col not in ["children","charges"]]

#Actualizamos el df eliminando los valores en 0 de estas columnas.
df = df[(df[cols_to_check] > 0).all(axis=1)]

#Categorizamos las columnas(categoricas) obteniendo la cantidad de valores unicos, es decir, cuantas regiones unicas hay?: 4
count_of_categories = {col: df[col].nunique() for col in df.select_dtypes(include="object").columns}
count_of_categories

#Categorizamos las columnas(categoricas) obteniendo sus valores unicos, es decir, cuantos sexos hay?: "female","Male"
unique_values_categories = {col: df[col].unique() for col in df.select_dtypes(include="object").columns}
unique_values_categories

{'sex': array(['female', 'male'], dtype=object),
 'smoker': array(['yes', 'no'], dtype=object),
 'region': array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)}

## Conclusiones

Eliminamos duplicados. Tambien iteramos osbre las columnas numericas excluyendo nuestra variable objetivo y children(porque no queremos eliminar los datos en 0 de esta columna). Creamos un diccionario con la cantidades unicas de las columnas categoricas y hacemos lo mismo pero obteniendo los valores reales(str, bool, etc)

### 8-CEEP CODIFICADO,ESCALADO,ENTRENAMIENTO Y PRUEBA

##### 8.1 Separar X e y:

In [136]:
X = df.drop("charges", axis=1) #Todas las columnas menos charges
y = df["charges"] #Variable objetivo

##### 8.2 Dividir en entrenamiento y prueba:

In [137]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train,X_test, y_train, y_test

(      age     sex     bmi  children smoker     region
 1114   23    male  24.510         0     no  northeast
 968    21    male  25.745         2     no  northeast
 599    52  female  37.525         2     no  northwest
 170    63    male  41.470         0     no  southeast
 275    47  female  26.600         2     no  northeast
 ...   ...     ...     ...       ...    ...        ...
 1096   51  female  34.960         2    yes  northeast
 1131   27    male  45.900         2     no  southwest
 1295   20    male  22.000         1     no  southwest
 861    38  female  28.000         3     no  southwest
 1127   35  female  35.860         2     no  southeast

 [1069 rows x 6 columns],
       age     sex     bmi  children smoker     region
 900    49    male  22.515         0     no  northeast
 1064   29  female  25.600         4     no  southwest
 1256   51  female  36.385         3     no  northwest
 298    31    male  34.390         3    yes  northwest
 237    31    male  38.390         2     no  southeast
 ...   ...     ...     ...       ...    ...        ...
 534    64    male  40.480         0     no  southeast
 542    63  female  36.300         0     no  southeast
 760    22  female  34.580         2     no  northeast
 1284   61    male  36.300         1    yes  southwest
 1285   47  female  24.320         0     no  northeast

 [268 rows x 6 columns],
 1114     2396.09590
 968      3279.86855
 599     33471.97189
 170     13405.39030
 275      9715.84100
            ...
 1096    44641.19740
 1131     3693.42800
 1295     1964.78000
 861      7151.09200
 1127     5836.52040
 Name: charges, Length: 1069, dtype: float64,
 900      8688.85885
 1064     5708.86700
 1256    11436.73815
 298     38746.35510
 237      4463.20510
            ...
 534     13831.11520
 542     13887.20400
 760      3925.75820
 1284    47403.88000
 1285     8534.67180
 Name: charges, Length: 268, dtype: float64)

##### 8.3 Seperar columnas categoricas y numericas

In [138]:
categorical_cols = X_train.select_dtypes(include="object").columns
numerical_cols = X_train.select_dtypes(exclude="object").columns

X_train_cat = X_train[categorical_cols]
X_test_cat = X_test[categorical_cols]

X_train_num = X_train[numerical_cols]
X_test_num = X_test[numerical_cols]

X_train_num, X_train_cat

(      age     bmi  children
 1114   23  24.510         0
 968    21  25.745         2
 599    52  37.525         2
 170    63  41.470         0
 275    47  26.600         2
 ...   ...     ...       ...
 1096   51  34.960         2
 1131   27  45.900         2
 1295   20  22.000         1
 861    38  28.000         3
 1127   35  35.860         2

 [1069 rows x 3 columns],
          sex smoker     region
 1114    male     no  northeast
 968     male     no  northeast
 599   female     no  northwest
 170     male     no  southeast
 275   female     no  northeast
 ...      ...    ...        ...
 1096  female    yes  northeast
 1131    male     no  southwest
 1295    male     no  southwest
 861   female     no  southwest
 1127  female     no  southeast

 [1069 rows x 3 columns])

#### 8.4 Escalar variables numericas

In [139]:
scaler = MinMaxScaler()
X_train_num = scaler.fit_transform(X_train[numerical_cols])
X_test_num = scaler.transform(X_test[numerical_cols])

##### 8.5 codificar variables categoricas

In [140]:
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[categorical_cols])
X_test_cat = encoder.transform(X_test[categorical_cols])
X_train_cat
#guardamos los nombres expandidos de las columnas categóricas
cat_cols = encoder.get_feature_names_out(categorical_cols)
cat_cols

array(['sex_female', 'sex_male', 'smoker_no', 'smoker_yes',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'], dtype=object)

## Conlusiones

Separamos nuestras variables numericas y categoricas en dos conjuntos diferentes, escalamos nuestras variables numericas para que esten en un rango en comun y codificamos nuestras variables categoricas para transformarlas a numericas con OneHotEncoder(convierte las categorias en binarios 0 o 1) y MinMaxScaler convierte las variables numericas en un rango entre 0 y 1(infinitas posibilidades dentro de ese rango). El metodo fit_transform aprende de ese escalado y codificacion, es decir, en el esacaldo aprende el minimo y el maximo numero y luego aplica lo que aprendio al conjunto de de entrenamiento(aprende y aplica), luego usamos solo tranform para el conjunto de test ya que aqui solo queremos aplicar la transformacion pero no queremos aprender nada, no queremos que el modelo "vea las respuestas" para el test(data leakage). lo mismo aplica para la codificacion.

In [141]:
X_train_final = pd.DataFrame(
np.concatenate([X_train_num, X_train_cat], axis=1),
columns = list(numerical_cols) + list(cat_cols)
)
X_test_final = pd.DataFrame(
    np.concatenate([X_test_num, X_test_cat], axis=1),
    columns = list(numerical_cols) + list(cat_cols)
)
X_train_final, X_test_final

(           age       bmi  children  sex_female  sex_male  smoker_no  \
 0     0.108696  0.230024       0.0         0.0       1.0        1.0
 1     0.065217  0.263250       0.4         0.0       1.0        1.0
 2     0.739130  0.580172       0.4         1.0       0.0        1.0
 3     0.978261  0.686306       0.0         0.0       1.0        1.0
 4     0.630435  0.286252       0.4         1.0       0.0        1.0
 ...        ...       ...       ...         ...       ...        ...
 1064  0.717391  0.511165       0.4         1.0       0.0        0.0
 1065  0.195652  0.805488       0.4         0.0       1.0        1.0
 1066  0.043478  0.162497       0.2         0.0       1.0        1.0
 1067  0.434783  0.323917       0.6         1.0       0.0        1.0
 1068  0.369565  0.535378       0.4         1.0       0.0        1.0

       smoker_yes  region_northeast  region_northwest  region_southeast  \
 0            0.0               1.0               0.0               0.0
 1            0.0               1.0               0.0               0.0
 2            0.0               0.0               1.0               0.0
 3            0.0               0.0               0.0               1.0
 4            0.0               1.0               0.0               0.0
 ...          ...               ...               ...               ...
 1064         1.0               1.0               0.0               0.0
 1065         0.0               0.0               0.0               0.0
 1066         0.0               0.0               0.0               0.0
 1067         0.0               0.0               0.0               0.0
 1068         0.0               0.0               0.0               1.0

       region_southwest
 0                  0.0
 1                  0.0
 2                  0.0
 3                  0.0
 4                  0.0
 ...                ...
 1064               0.0
 1065               1.0
 1066               1.0
 1067               1.0
 1068               0.0

 [1069 rows x 11 columns],
           age       bmi  children  sex_female  sex_male  smoker_no  \
 0    0.673913  0.176352       0.0         0.0       1.0        1.0
 1    0.239130  0.259349       0.8         1.0       0.0        1.0
 2    0.717391  0.549502       0.6         1.0       0.0        1.0
 3    0.282609  0.495830       0.6         0.0       1.0        0.0
 4    0.282609  0.603444       0.4         0.0       1.0        1.0
 ..        ...       ...       ...         ...       ...        ...
 263  1.000000  0.659672       0.0         0.0       1.0        1.0
 264  0.978261  0.547215       0.0         1.0       0.0        1.0
 265  0.086957  0.500942       0.4         1.0       0.0        1.0
 266  0.934783  0.547215       0.2         0.0       1.0        0.0
 267  0.630435  0.224913       0.0         1.0       0.0        1.0

      smoker_yes  region_northeast  region_northwest  region_southeast  \
 0           0.0               1.0               0.0               0.0
 1           0.0               0.0               0.0               0.0
 2           0.0               0.0               1.0               0.0
 3           1.0               0.0               1.0               0.0
 4           0.0               0.0               0.0               1.0
 ..          ...               ...               ...               ...
 263         0.0               0.0               0.0               1.0
 264         0.0               0.0               0.0               1.0
 265         0.0               1.0               0.0               0.0
 266         1.0               0.0               0.0               0.0
 267         0.0               1.0               0.0               0.0

      region_southwest
 0                 0.0
 1                 1.0
 2                 0.0
 3                 0.0
 4                 0.0
 ..                ...
 263               0.0
 264               0.0
 265               0.0
 266               1.0
 267               0.0

 [268 rows x 11 columns])

### conclusiones
Unimos todo en matrices finales separando train y test. Una para entrenar el modelo y otra para evaluarlo.

In [142]:
selection_model = SelectKBest(f_regression, k=4) 
selection_model.fit(X_train_final, y_train)

selected_columns = X_train_final.columns[selection_model.get_support()]
selected_columns

X_train_sel = pd.DataFrame(selection_model.transform(X_train_final), columns=selected_columns)
X_test_sel = pd.DataFrame(selection_model.transform(X_test_final), columns=selected_columns)
X_train_sel.head()

        age       bmi  smoker_no  smoker_yes
0  0.108696  0.230024        1.0         0.0
1  0.065217  0.263250        1.0         0.0
2  0.739130  0.580172        1.0         0.0
3  0.978261  0.686306        1.0         0.0
4  0.630435  0.286252        1.0         0.0

## Conclusiones

Creamos un modelo de seleccion(SeelectKBest) que va a elegir las 4 cracateisticas mas relevantes(f_regression, k=4). Lo entrenamos con el metodo .fit y los datos de entrenamiento, retornamos una lista con valores boleanos que determina las variables elegidas, estas variables seran las nuevas columnas de nuestro df de entrenamiento y prueba de nuestras variables predictoras

# 1-Entrenar y optimizar el modelo

In [143]:
model = LinearRegression()
model.fit(X_train_sel, y_train)

LinearRegression()

## Conclusiones

En este punto podemos agregar que inicializamos una instancia del modelo LinearRegression y lo entrenamos con el método fit pasandole como parametros el df con nuestras 4 variables de entrenamiento mas relevantes ya escaladas y nuestra variable objetivo

### 1.1 Interpretar los parametros del modelo

In [144]:
print(f"Intercepto (a): {model.intercept_}")
print(f"Coeficientes (b1,b2):{model.coef_}")

Intercepto (a): 10164.663045081
Coeficientes (b1,b2):[ 11586.30415359  11329.51105637 -11537.13086749  11537.13086749]

### 1.2-Predecir sobre el conjunto de prueba

In [ ]:
y_pred = model.predict(X_test_sel) #Probamos el modelo con los datos de entrenamiento
y_pred

array([ 8433.67443577,  4336.46678013, 13165.0382606 , 30593.69534864,
        8738.64384303, 13004.1887831 , 29273.63576136,  2177.09021482,
       10922.95093736, 10315.83022735, 11021.84491859, 33740.33309282,
       30613.92158231, 18004.87150727,  9656.23179762,  9311.37354392,
        4325.12010919, 32099.96630635,  3001.71338943,  5552.62898392,
        4325.12010919, 29913.00795743, 14580.01800456, 30752.45719245,
       31444.92261851,  4769.02189756, 35187.05259131, 37413.46842278,
       10952.8675722 , 12177.75978526,  6505.9651105 , 13121.95183512,
         870.87899962, 12471.87695664, 40355.37672202, 12499.04467281,
        2732.11267963,  2866.20850841, 32023.18474965,  9365.1280589 ,
        6903.0538664 , 29243.81679061, 34097.79751626, 11919.91981386,
        6896.22734444,  4145.55111435,  6040.33037213,  9173.38425823,
        4186.69945959,  8909.59778913,  6340.1295272 , 12053.6361681 ,
       30836.41015271,  4425.70495311, 10719.84316929,  9666.05445578,
       10530.02015238,  2388.64618173, 31511.97918113,  8879.94566829,
       14211.20691017,  8472.07386235, 11998.05853343,  1725.85017296,
       15951.34770214,  9817.6103031 , 10093.34165695, 31607.56062279,
       25532.05211301, 16080.45742511,  7915.22827784,  2942.01237675,
        6853.00866197,  -356.23310413, 11913.95601971,  -315.91289378,
       17821.98997286,  8437.71744615,  8063.3393286 , 13057.51193418,
        5353.67918676, 16576.19294469, 15605.66131355, 10822.36609344,
       36626.79601439, 13142.44258279,  4545.67059936,  2714.93447154,
        6601.99521252,  4946.63551571, 14433.69548057, 27069.76371833,
        3688.34727834,  3997.87142749,  2823.55344684, 36048.10251934,
       15218.71161918,  9264.54321498,  5063.57043284,  7889.46961392,
       14790.03266221, 14337.55041802, 32626.69381319, 13734.32316493,
       31514.33132881,   645.73917464, 30596.46156376, 25426.19935283,
       13303.85568118,  6304.92767965,  7936.44949632, 12119.41593546,
        7927.58723005,  8602.31082711,  6810.08908641,  6204.36013219,
        1861.90137843,  3921.95259861,  7796.53942685,  8997.9732343 ,
       36885.61367413,  8283.79215469, 11912.44930338,  8505.60214366,
        8989.80684593,  9370.67778561,  2810.79772364, 13188.99110128,
       30586.22483816, 39662.6294855 , 36528.43106115, 12232.90605603,
        3371.63442915, 10393.96894692,  9397.84550177,  3318.44353507,
       35257.98531439, 29553.60545375, 25891.71913067,  5634.37934996,
        6372.26605272,  4725.37185119, 37215.92767786, 10590.6988534 ,
        6302.46057144,  9049.80696551, 10482.94260591,  8693.73429786,
       35306.47191312, 14632.64527774,  9407.53590294,  5469.07279464,
        7341.25637461, 17449.84904246,  6915.07911878, 27181.03394822,
       36131.39419463, 15467.27525687, 10807.67229001, 11639.08739366,
       12791.3733174 ,  4348.50932897, 13286.39566263, 14030.52796999,
       36157.96369698, 32941.4858786 , 12233.86644792, 25521.79809094,
        2678.2086112 ,   686.19164198,  4942.32799134,  5698.9515079 ,
        5298.53291599, 10778.28468316,  9412.65426574, 25778.2290101 ,
        2565.29940799, 11478.23791616,  7032.2785499 , 10700.99139495,
       14438.68158638,  5437.78170048, 10373.4609028 , 10651.37755442,
       32368.3248138 , 11508.56861844,  6330.43912604,  4989.30787374,
         877.38911821, 31175.86823316,  8121.98228531, 32755.82083261,
       12713.23459784,  6308.25751568,  1783.76265886,  2949.63244069,
       32368.3248138 ,  4663.71546183, 12572.46180056, 16456.88858342,
       26818.31890499, 26647.89398687,  7416.34706861, 13140.78631301,
       27652.9142912 ,  8064.74838085,  9632.80798492,  9996.35116305,
        3593.31216112, 33576.03881877, 31272.27780971,  8662.55816423,
        6157.79431724,  7073.16238115, 11818.48953859,  5430.72525744,
        5406.05924241, 12357.4610371 ,  9872.75657387,  2999.92486265,
        4241.84573036, 36798.06636386, 36763.70994766, 13152.13298395,
       11228.0180087 , 38750.15989371, 34597.52415685,  7576.48337175,
       27058.69885784,  4140.28319809, 16680.91846307, 30255.08269954,
        5188.67173835, 10201.67882181,  9174.6091641 , 10127.96258714,
        9930.23769586,  4994.85760045,  6037.1327931 ,  4897.58529609,
        5377.5170669 ,  5246.58422424,  5567.86911179,  9625.86650242,
        1688.16392074,  8462.63067872,  2932.71874658, 10063.68953611,
        2652.44994728,  9238.91680805,  3715.10092706, 12050.00722517,
       13150.47671417, 13538.27183989, 35912.05131388, 23410.21224647,
       10361.81512495,  6332.22765282,  8048.94463209, 11610.13115071,
       28199.48855719, 38867.09481084, 13593.8321781 , 17687.59503718,
       16161.64417025,  5310.46050429, 38732.15355072,  8480.09069727])

### 1.3 - Evaluar el rendimiento del modelo

In [146]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Error cuadrático medio (MSE): {mse:.4f}")
print(f"Coeficiente de determinación (R²): {r2:.4f}")

Error cuadrático medio (MSE): 35841574.8181
Coeficiente de determinación (R²): 0.8050

## Conclusiones

MSE(Error cuadratico medio): Medida de cuanto se equivoca el modelo

r2(Coeficiente de determinación): Que tan bien se ajusta el modelo a los datos reales?

Los datos estan escalados entre 0 y 1 por lo tanto los valores mse y r2 reflejan ese rango.
El modelo predice con bastante precisión